### PR TITLE
[ISSUE-70] Docbuild automations

### PR DESCRIPTION
**Pull request by xBalbinus**
## What is the purpose of the change

Automating the process for docbuild on docs side.

## Brief change log

Added placeholders for content in spec-XXXX.md in modules folder
Added docbuild steps in docbuild.yml and docbuild_stage.yml

## Verifying this change

This change has been tested locally by rebuilding the doc website and verified content and links are expected.

### CODE REVIEW

**Comment by daniel-farina** [comment]
Why is this adding changes from stage? 
Can we create a PR only for the changes related to this PR.

image

**Comment by xBalbinus** [comment]
Ah shoot sorry, unintended. Will fix asap

**Comment by xBalbinus** [comment]
I may end up closing with comment on this PR to combine the changes here with the ones made on #90

**Comment by daniel-farina** [comment]
I'm closing this PR.

**Pull request closed without merging**
