### PR TITLE
Documented superfluid state machine

### PR DESCRIPTION
**Pull request by xBalbinus**
Includes tabs, diagrams, images. All set to go on the frontend (unless any error is to be spotted)

### CODE REVIEW

**Comment by daniel-farina** [comment]
> Should this go in the code inside the spec folder, and then get automatically duplicated into here?

I agree. I think that would make more sense. @xBalbinus let's setup a call to explain this idea and demo how it would work.

**Comment by czarcas7ic** [comment]
@daniel-farina did this call with @xBalbinus occur yet? If not I would like to sit in on it if possible.

**Comment by xBalbinus** [comment]
Hey @czarcas7ic ! The call did happen, sorry I was slow to move on this; I'll be sure to handle the rest with @daniel-farina.

**Comment by daniel-farina** [comment]
@xBalbinus @czarcas7ic 
Invite sent to both for today.

**Comment by daniel-farina** [comment]
@xBalbinus I think the only thing missing now is adding a place holder file for the superfluid staking doc on this repo. We can probably abandon this PR.

**Comment by xBalbinus** [comment]
Hmm... I think the placeholder was already added in?
Screen Shot 2022-04-19 at 10 16 05 AM

**Comment by daniel-farina** [comment]
ahh I missed that! and also we need the actual section with custom html from this PR as well.

**Review by daniel-farina — APPROVED** [review]
lgtm

**Comment by xBalbinus** [comment]
Thanks @daniel-farina for moving the diagram! I had missed that.

**Pull request merged**
