### PR TITLE
[issue-64] add umbrella section of 'Getting Started' for contributing to Osmosis

### PR DESCRIPTION
**Pull request by jblbit**
## What is the purpose of the change

for https://github.com/osmosis-labs/docs/issues/64

Created section of "Getting Started" and write a starter guidance for new contributors to get up to speed quickly. 

## Brief change log

- added section of "Getting Started"
- added new page of "Build and Test Osmosis Source Code" to show how to build and test code
- moved ide-guide.md to this section
- A tiny extra work in `.gitignore` to ignore DS_Store files from mac

note: more future work mentioned in issue64, as I learn how to do it exactly, will be added in separate PRs later on

## Verifying this change

This change has been tested locally

image

image

### CODE REVIEW

**Comment by jblbit** [comment]
cc @xBalbinus @daniel-farina @ValarDragon hi guys, can you help review?

**Comment by czarcas7ic** [comment]
Screen Shot 2022-04-16 at 8 19 01 PM

nit: can we change this to say GET STARTED instead of GET_STARTED like the other ones

**Comment by xBalbinus** [comment]
Besides for @czarcas7ic 's good pointer, it looks good to me.

**Comment by jblbit** [comment]
@czarcas7ic @xBalbinus thanks for catching that! fixed, with screenshot below

image

**Comment by daniel-farina** [comment]
looks great, thank you @jlbit

**Pull request merged**
